### ISSUE TITLE
Trophy for mruby

### ISSUE THREAD

**Issue by lopopolo** [rust-fuzz/trophy-case#115]
Hi folks, thanks so much for the tools in this organization! I have a trophy for y'all but since the codebase isn't pure Rust (and the trophy is not in Rust code) I wasn't sure if you would be open to including it in this list.

I run `cargo-fuzz` on Artichoke Ruby. Artichoke Ruby is a hybrid Rust and C codebase; the C part is the `mruby` third party library that I'm oxidizing.

I know this trophy case is focused around Rust code, but `cargo-fuzz` found an infinite loop in a bison parser that comes from Artichoke's mruby C dep.

I'm not sure if y'all want to include it here.

Links:

- https://github.com/mruby/mruby/issues/5676
- https://github.com/mruby/mruby/commit/b4168c9b68daf759ce890c7da9e4ad5547058330

Thanks again!

**Comment by Manishearth** [comment]
I think it's fine to add, note that it was found in C code.

**Comment by lopopolo** [comment]
thanks @Manishearth. PR is here: https://github.com/rust-fuzz/trophy-case/pull/116
