### ISSUE TITLE
Trophy case has been going on for long enough: enough people have tried fuzzing now?

### ISSUE THREAD

**Issue by chrish42** [rust-fuzz/trophy-case#81]
Hi. Near the top of the README, you wrote:

"These bugs aren't nearly as serious as the memory-safety issues afl has discovered in C and C++ projects. That's because Rust is memory-safe by default, **but also because not many people have tried fuzzing yet!**" [Emphasis mine]

This was added back in April 2017, which is almost two years and a half ago, now. I personally think that would start being long enough (plus, the list is getting pretty long too) to remove that "not many people have tried fuzzing yet" and potentially add some comment instead on the effectiveness (it seems) of Rust's memory safety guarantees for security bugs. (If not, then at least some kind of discussion here on when will be "long enough" for that would be valuable...)

**Comment by frewsxcv** [comment]
Yep, good catch. Thanks!
